=== sourav-py/web-tech-lab/xml/employee.dtd
<!-- root = employees -->
<!ELEMENT employees (employee+)>

<!ELEMENT employee (id,name,department,salary,projects+)>

<!ELEMENT id (#PCDATA)>

<!-- name -->
<!ELEMENT name (first_name,middle_name?,last_name)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>

<!ELEMENT department (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

<!-- project -->
<!ELEMENT projects (project_id,project_name,project_location+)>
<!ELEMENT project_id (#PCDATA)>
<!ELEMENT project_name (#PCDATA)>
<!ELEMENT project_location (#PCDATA)>


<!-- SOURAV SINGH UE183106 -->

=== sourav-py/web-tech-lab/xml/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<?xml-stylesheet type = "text/css" href = "emp.css"?>

<employees>
    <employee>
        <id>ID 001</id>
        <name>
            <first_name>SOURAV</first_name>
            <last_name>SINGH</last_name>
        </name>
        <department>UIET</department>
        <salary>SALARY NA</salary>
        <projects>
            <project_id>PROJECT ID 101</project_id>
            <project_name>NAME p1</project_name>
            <project_location>LOCATION UIET,Panjab University</project_location>
        </projects>
    </employee> 

    <employee>
        <id>ID 002</id>
        <name>
            <first_name>SOUMEL</first_name>
            <last_name>ZUTSHI</last_name>
        </name>
        <department>UIET</department>
        <salary>SALARY NA</salary>
        <projects>
            <project_id>PROJECT ID 101</project_id>
            <project_name>NAME p1</project_name>
            <project_location>LOCATION UIET,Panjab University</project_location>
        </projects>
    </employee>

    <employee>
        <id>ID 001</id>
        <name>
            <first_name>SURAJ</first_name>
            <last_name>GAUR</last_name>
        </name>
        <department>UIET</department>
        <salary>SALARY NA</salary>
        <projects>
            <project_id>PROJECT ID 101</project_id>
            <project_name>NAME p1</project_name>
            <project_location>LOCATION UIET,Panjab University</project_location>
        </projects>
    </employee>

    <employee>
        <id>ID 001</id>
        <name>
            <first_name>SOPHIA</first_name>
            <last_name>GARG</last_name>
        </name>
        <department>UIET</department>
        <salary>SALARY NA</salary>
        <projects>
            <project_id>PROJECT ID 101</project_id>
            <project_name>NAME p1</project_name>
            <project_location>LOCATION UIET,Panjab University</project_location>
        </projects>
    </employee>
</employees>
